version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.22
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
            migrations: true
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
  api:
    restart: on-failure
    depends_on:
      - prisma
    build:
      dockerfile: Dockerfile
      context: ./api
    ports:
      - '4000:4000'
    volumes:
      - /usr/app/node_modules
      - ./api:/usr/app
  web:
    depends_on:
      - api
    build:
      dockerfile: Dockerfile
      context: ./web
    ports:
      - '3000:3000'
      - '35729:35729'
    volumes:
      - /usr/app/node_modules
      - ./web:/usr/app
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  mysql:
